### DISCUSSION TITLE
Accessing solargraph config from plugins/conventions

### DISCUSSION THREAD

**Discussion by grncdr** [castwide/solargraph#584] [Q&A]
Hi, I'm interested in writing a configurable plugin that registers a convention. What I'd like to do is add a key into `.solargraph.yml` like:

```yml
my-plugin:
  setting1: foo
  setting2:
    - bar
```

Is there a way for me to access either the loaded config, or at least the path of the config file so that I can load it myself?
