### ISSUE TITLE
Is require_paths relative to workspace?

### ISSUE THREAD

**Issue by thomthom** [castwide/solargraph#162]
I'm trying to help out on a reported issue in a VSCode + Solargraph setup example I've provided:
https://github.com/SketchUp/sketchup-ruby-api-tutorials/issues/15

Given a `.solargraph.yml` like this: (Example project at https://github.com/SketchUp/sketchup-ruby-api-tutorials/issues/15#issuecomment-466405372)

```yml
require_paths:
- "C:/Program Files/SketchUp/SketchUp 2018/Tools"
- src

# This will load the stubs for the SketchUp API.
require:
- sketchup-api-stubs/autoload/sketchup.rb
```

And a `src/sample.rb` like this: (Along with a dummy `src/sample/main.rb`)

```ruby
require 'sketchup.rb'
require 'sample/main'

module Example

  def self.hello
    model = Sketchup.active_model
    model.save
  end

end
```

`require 'sketchup.rb` is flagged as not resolved:
![image](https://user-images.githubusercontent.com/192418/53334376-e534d300-38f8-11e9-8a5b-f29942f93139.png)

`sketchup.rb` is located in the `C:/Program Files/SketchUp/SketchUp 2018/Tools` directory.

I've used this setup for my own projects, but not seen this issue. For example, this project have similar setup but does not yield the require warning:

https://github.com/thomthom/true-bend

I looked around in the source code for solargraph, and I now I'm wondering how I don't see that in all my projects. There are two things which appear to not make this scenario work:

1. It appear that `.rb` is automatically appended to the path when checking if a path can be required:

https://github.com/castwide/solargraph/blob/bf6d14707926096e4abdd5753c9dc1d5641046b1/lib/solargraph/workspace.rb#L93-L102

In my case, `require 'sketchup.rb` includes the file extension for legacy reasons. So it then looks like solargraph looks for `sketchup.rb.rb`. Am I reading the code right?

2. It appear the `require_paths` in `.solargraph.yml` is always prefixed with the path of the workspace?

https://github.com/castwide/solargraph/blob/bf6d14707926096e4abdd5753c9dc1d5641046b1/lib/solargraph/workspace.rb#L174-L181

So if I understand the code correctly, solargraph expects `require` statements to omit `.rb` and `require_paths` to be relative to the workspace? If that is correct, then I'm confused to why I don't see the same require warning in my other projects. Any ideas?

**Comment by thomthom** [comment]
Oooh.....

I just realized that I have inadvertently omitting `require_not_found` reporters:

https://github.com/thomthom/true-bend/blob/07caec6f95759fad7e8f6902527fdccf10011495/.solargraph.yml#L8-L9

```yml
require_paths:
- "C:/Program Files/SketchUp/SketchUp 2018/Tools"
- src

require:
- sketchup-api-stubs/autoload/sketchup.rb

reporters:
- rubocop
```

Aaand... I just realized I've had this discovery before..... https://github.com/castwide/vscode-solargraph/issues/56#issuecomment-391794165(*facepalm*)

I'm sorry for the noise.
