### ISSUE TITLE
Reporters aren't with LanguageServer in Neovim

### ISSUE THREAD

**Issue by wh1le** [castwide/solargraph#238]
Hello, thanks for the nice tool. I'm having troubles with my setup. I'm use the [LanguageClient for Neovim](https://github.com/autozimu/LanguageClient-neovim) and solargraph. Having troubles with Rubocop setup. I have this in my project root directotry:
```yaml
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
require_paths: []
max_files: 5000
```

Autocomplete works perfectly but there are not any kinds of warnings from Rubocop. What is the problem? For example `javascript-typescript-stdio` works perfectly and shows all there
errors. NVIM detects LC root directory correctly. There are no errors in LanguageServer logs.
Ruby - **2.6.5**
Solargraph - **0.37.2**
Neovim - **0.4.2**
Rubocop -**0.75.1**

```bash
$ solargraph reporters
rubocop
require_not_found
typecheck
update_errors
```
Also serverCommands settings from my `.vimrc`
```vim
let g:LanguageClient_serverCommands = {
    \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'javascript.jsx': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'ruby': ['~/.rbenv/shims/solargraph', 'stdio'],
    \ 'ruby.spec': ['~/.rbenv/shims/solargraph', 'stdio'],
    \ }
```
