### ISSUE TITLE
max_files not taken into account

### ISSUE THREAD

**Issue by vadviktor** [castwide/solargraph#269]
Hello,

I seem to have a little problem with setting max_files in a large project. I have to index around ~12k files and setting `max_files` to 20000 or 0 will still result in the same error message:

![Screenshot 2020-01-27 at 12 00 48](https://user-images.githubusercontent.com/238703/73173355-15828400-40fd-11ea-85de-4729f44cfbca.png)

I am using VSCode v1.41.1 on a ruby:2.5.5 Docker container.

![Screenshot 2020-01-27 at 12 01 57](https://user-images.githubusercontent.com/238703/73173454-4cf13080-40fd-11ea-8a4e-11319b036624.png)

Could you help me track down the real issue, please?

**Comment by castwide** [comment]
Can you copy/paste your workspace's `.solargraph.yml` file?

**Comment by vadviktor** [comment]
Sure:

```yaml
---
include:
  - "lib/**/*.rb"
  - "app/**/*.rb"
  - "/usr/local/lib/ruby/gems/2.5.0/gems/**/*.rb"
  - "/usr/local/bundle/gems/**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths: []
max_files: 20000
```
