### ISSUE TITLE
`require_paths` Not Working

### ISSUE THREAD

**Issue by deiden26** [castwide/solargraph#379]
I have a `.solargraph.yml` set up in a Rails project that contains the following

```yml
include:
  - "**/*.rb"
exclude:
  - spec/**/*
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck
  - update_errors
require_paths:
  - spec
max_files: 5000
```

The goal is to prevent `RequireNotFound` errors whenever I `require 'rails_helper'` in a Rails-related spec. Here's a simplified version of the file structure

```
project/
  .solargraph.yml
  app/
    <APP STUFF>
  spec/
    spec_helper.rb
    rails_helper.rb
    example_spec.rb
    <OTHER SPECS>
```

Is there something wrong with my configuration?
