### ISSUE TITLE
Reek config

### ISSUE THREAD

**Issue by nomasprime** [castwide/solargraph#388]
Seems like I can't configure Reek in the normal way.

Have the same `.reek.yml` in home and project directory:

```yml
---
detectors:
  IrresponsibleModule:
    enabled: false
```

Yet still I'm getting errors coming through from Solargraph, works as expected on the command line.
