### ISSUE TITLE
[Question] How to specify rubocop version?

### ISSUE THREAD

**Issue by gniw** [castwide/solargraph#444]
I want to use old version (0.81.0) of rubocop to support ruby 2.3.
It's too old, but I absolutely have to use... 😭  

According to [Rubocop Version](https://github.com/castwide/solargraph#rubocop-version) section, configure `.solargraph.yml`.

```yaml
reporters:
  - rubocop:version=0.81.0
  - require_not_found
formatter:
  rubocop:
    version: 0.81.0
```

Yes, solargraph is work, but rubocop said 

```
Error in diagnostics: Error in RuboCop configuration: 
RuboCop found unsupported Ruby version 2.3 in `TargetRubyVersion` parameter (in .rubocop.yml).
2.3-compatible analysis was dropped after version 0.81
```

It doesn't seem to recognize rubocop version correctly.
Was my procedure wrong?

Please let me know if there is a correct way.
