### ISSUE TITLE
Unable to remove Rubocop from reporters

### ISSUE THREAD

**Issue by samtgarson** [castwide/solargraph#452]
Hello there, thanks for your work on OSS 🙌 

I'm trying to remove the `Rubocop` reporter from my Solargraph config, as I have [other methods](https://github.com/mattn/efm-langserver) of getting Rubocop diagnostics in my IDE, and at the moment I'm getting duplicated diagnostics.

(I'd still like to receive diagnostics from the other reporters and other solargraph functionality.)

With the following config (both globally and locally):
```yaml
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- require_not_found
- typecheck
- update_errors
max_files: 5000
```

I still get the following response to `solargraph reporters`:
```
❯ solargraph reporters
rubocop
require_not_found
typecheck
update_errors
```

Is there something I'm missing, should I be able to remove Rubocop from the reporters array? Thanks!
