### ISSUE TITLE
typecheck: use domains from config when checking types

### ISSUE THREAD

**Issue by pdspicer** [castwide/solargraph#485]
It's very possible that I'm just going about this all wrong, but I'm trying to set up my workspace config so that typecheck includes types from domains that I've specified in the config file (my code executes entirely within the context of one domain). So far I haven't been able to make this work, and I'm not sure if its something I'm doing incorrectly, or if the "domains" config value is unused during typechecking. I'm leaning towards it not being used, as I tested out some invalid values under "domains", and received no complaint from solargraph. Any assistance clarifying the intended behavior would be much appreciated.

My command:

```shell
bundle exec solargraph typecheck --level strict
```

My Config (with sample domain):

```yaml
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
domains:
  - "Module::Hierarchy::Here"
reporters:
  - typecheck:strict
  - require_not_found
  - rubocop
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
plugins: []
max_files: 5000
```

Apologies if any of my terminology here is terrible, I'm not much of a Ruby dev.
