### ISSUE TITLE
Rubocop extra_args not being picked up

### ISSUE THREAD

**Issue by dgmora** [castwide/solargraph#486]
I may be doing something wrong, but I've tried with the following config:
```
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
domains: []
reporters:
- rubocop
formatter:
  rubocop:
    cops: all
    except:
      - 'RSpec/Focus'
    only: []
    extra_args:
      - '-D'
      - '--config'
      - '.rubocop.local.yml'
require_paths: []
plugins: []
max_files: 5000
```
`extra_args` does not seem to pick up `-D` (to show the cop name), it only shows the error message. `--config` also does not seem to work, it's picking up `rubocop.yml` instead of `rubocop.local.yml`. Are the extra args specified incorrectly?
