### ISSUE TITLE
Solargraph does not seem to parse return type from override macro

### ISSUE THREAD

**Issue by alisnic** [castwide/solargraph#514]
here's a modification to a spec:

```diff
diff --git a/spec/source_map/mapper_spec.rb b/spec/source_map/mapper_spec.rb
index 559cbd08..2b122559 100644
--- a/spec/source_map/mapper_spec.rb
+++ b/spec/source_map/mapper_spec.rb
@@ -1182,6 +1182,7 @@ describe Solargraph::SourceMap::Mapper do
     pins, _locals = Solargraph::SourceMap::Mapper.map(source)
     over = pins.select { |pin| pin.is_a?(Solargraph::Pin::Reference::Override) }.first
     expect(over.name).to eq('Foo#bar')
+    expect(over.return_type.tag).to eq('String')
```

test output

```
Failures:

  1) Solargraph::SourceMap::Mapper processes override directives
     Failure/Error: expect(over.return_type.tag).to eq('String')

       expected: "String"
            got: "undefined"
```
