### ISSUE TITLE
Unresolved type for ActiveSupport 

### ISSUE THREAD

**Issue by thornomad** [castwide/solargraph#534]
Hello and thank you!  

With Solagraph version `0.4.3` and type checking enabled I am seeing this error even though `ActiveSupport::Duration` is a valid type.

```
[Typecheck] [E] Unresolved type ActiveSupport::Duration for interval param on OctocastCycle::OctocastShifter#shift_upcoming_octocasts_by
```
<img width="633" alt="image" src="https://user-images.githubusercontent.com/124717/152568589-2b67b060-1d31-4e4f-b756-395df933ea25.png">

  I have run `solgraph bundle` to install required documentation. My solargraph.yml file:

```yml
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
- actioncable
- actionmailer
- actionpack
- actionview
- activejob
- activemodel
- activerecord
- activestorage
- activesupport
domains: []
reporters:
- rubocop
- typecheck
require_paths: []
max_files: 5000
```

Is there something else I'm missing?  I've looked over the documentation and some of the current issues but don't see this mentioned. Thanks again.
